[project]
name = "src"
version = "0.0.1"
description = "An MLOps project for Vehicle Insurance data"
authors = [{name = "Sourav Kumar", email = "skumar.choudhary2612@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}